export const cvEditor = {
  sectionTitles: {
    contact: 'Thông tin liên hệ',
    summary: 'Tóm tắt chuyên môn',
    experience: 'Kinh nghiệm làm việc',
    skills: 'Kỹ năng',
    education: 'Học vấn',
    projects: 'Dự án',
    achievements: 'Thành tích',
    languages: 'Ngôn ngữ',
    certifications: 'Chứng chỉ',
  },
  header: {
    backToWorkspace: 'Quay lại CV Workspace',
    autoSave: {
      saving: 'Đang lưu...',
      saved: 'Đã lưu tự động',
      error: 'Lưu thất bại',
      offline: 'Chế độ offline',
    },
    userMenu: {
      profile: 'Hồ sơ',
      settings: 'Cài đặt',
      logout: 'Đăng xuất',
    },
  },
  editorPanel: {
    title: 'Chỉnh sửa CV',
    addSection: 'Thêm phần mới',
    deleteSection: 'Xóa phần',
    reorderSections: 'Kéo để sắp xếp lại các phần',
    cvScore: {
      title: 'Điểm CV',
      outOf: 'trên 100',
      improving: 'Tiếp tục cải thiện!',
    },
    jobAnalysis: {
      title: 'Phân tích mô tả công việc',
      placeholder: 'Dán mô tả công việc vào đây để nhận đề xuất tối ưu hóa...',
      analyzeButton: 'Phân tích công việc',
      analyzing: 'Đang phân tích...',
      maxLength: 'Tối đa 5000 ký tự',
      errors: {
        required: 'Vui lòng nhập mô tả công việc để phân tích',
        tooLong: 'Mô tả công việc quá dài (tối đa 5000 ký tự)',
        analysisFailed: 'Phân tích thất bại. Vui lòng thử lại.',
      },
    },
    suggestions: {
      title: 'Đề xuất tối ưu hóa',
      apply: 'Áp dụng',
      dismiss: 'Bỏ qua',
      noSuggestions: 'Không có đề xuất nào',
    },
  },
  sections: {
    contact: {
      title: 'Thông tin liên hệ',
      fields: {
        fullName: 'Họ và tên',
        email: 'Email',
        phone: 'Số điện thoại',
        location: 'Địa chỉ',
        linkedin: 'LinkedIn',
        website: 'Website',
      },
      placeholders: {
        fullName: 'Họ và tên đầy đủ',
        email: 'email@example.com',
        phone: '+84 123 456 789',
        location: 'Thành phố, Tỉnh/Quốc gia',
        linkedin: 'linkedin.com/in/yourprofile',
        website: 'website.com',
      },
    },
    summary: {
      title: 'Tóm tắt chuyên môn',
      placeholder: 'Viết một tóm tắt hấp dẫn nổi bật những thế mạnh và mục tiêu nghề nghiệp của bạn...',
      aiHelper: 'Tạo bằng AI',
      characterCount: 'ký tự',
      recommended: 'Khuyến nghị: 150-300 ký tự',
    },
    experience: {
      title: 'Kinh nghiệm làm việc',
      addExperience: 'Thêm kinh nghiệm làm việc',
      fields: {
        title: 'Chức danh',
        company: 'Công ty',
        location: 'Địa điểm',
        startDate: 'Ngày bắt đầu',
        endDate: 'Ngày kết thúc',
        current: 'Tôi hiện đang làm việc ở đây',
        description: 'Mô tả công việc',
        achievements: 'Thành tích chính',
      },
      placeholders: {
        title: 'vd: Kỹ sư phần mềm',
        company: 'vd: Công ty Công nghệ ABC',
        location: 'vd: Hồ Chí Minh, Việt Nam',
        startDate: 'MM/YYYY',
        endDate: 'MM/YYYY',
        description: 'Mô tả trách nhiệm và nhiệm vụ chính của bạn...',
        achievements: 'Liệt kê những thành tích và hoàn thành chính...',
      },
      bullets: {
        add: 'Thêm thành tích',
        placeholder: 'Mô tả một thành tích hoặc trách nhiệm cụ thể...',
        remove: 'Xóa',
        aiGenerate: 'Tạo bằng AI',
      },
    },
    skills: {
      title: 'Kỹ năng',
      addSkill: 'Thêm kỹ năng',
      categories: {
        technical: 'Kỹ năng kỹ thuật',
        soft: 'Kỹ năng mềm',
        languages: 'Ngôn ngữ',
        tools: 'Công cụ & Phần mềm',
      },
      placeholder: 'vd: JavaScript, Quản lý dự án, Tiếng Anh',
      aiSuggestions: 'Gợi ý AI',
    },
    education: {
      title: 'Học vấn',
      addEducation: 'Thêm học vấn',
      fields: {
        degree: 'Bằng cấp',
        institution: 'Trường học',
        location: 'Địa điểm',
        graduationDate: 'Ngày tốt nghiệp',
        gpa: 'GPA (tùy chọn)',
        description: 'Mô tả',
      },
      placeholders: {
        degree: 'vd: Cử nhân Khoa học Máy tính',
        institution: 'vd: Đại học Bách Khoa',
        location: 'vd: Hà Nội, Việt Nam',
        graduationDate: 'MM/YYYY',
        gpa: 'vd: 3.8/4.0',
        description: 'Khóa học liên quan, danh hiệu, hoạt động...',
      },
    },
  },
  preview: {
    title: 'Xem trước CV',
    pageCounter: 'Trang {{current}} / {{total}}',
    actions: {
      download: 'Tải PDF',
      print: 'In',
      share: 'Chia sẻ',
    },
    downloading: 'Đang chuẩn bị tải...',
    formats: {
      pdf: 'PDF',
      word: 'Word',
    },
  },
  notifications: {
    parsing: {
      success: 'Phân tích CV thành công!',
      successMessage: 'CV của bạn đã được phân tích và điền tự động.',
      error: 'Phân tích thất bại',
      errorMessage: 'Không thể trích xuất thông tin CV. Vui lòng điền thủ công.',
    },
    save: {
      success: 'CV đã được lưu thành công',
      error: 'Lưu CV thất bại',
      offline: 'Thay đổi đã được lưu cục bộ (offline)',
    },
  },
  errors: {
    loadFailed: 'Không thể tải dữ liệu CV',
    saveFailed: 'Không thể lưu CV',
    validationFailed: 'Vui lòng điền vào các trường bắt buộc',
    networkError: 'Lỗi mạng. Vui lòng kiểm tra kết nối.',
  },
} as const