import React from 'react';
import { render, screen } from '@testing-library/react';
import { AIPreview } from '../AIPreview';

// Mock the aiService to avoid actual API calls in tests
jest.mock('../../../utils/aiService', () => ({
  aiService: {
    generateBulletFromWizard: jest.fn().mockResolvedValue({
      success: true,
      data: 'Developed innovative solutions using modern technologies\nImproved system performance by 50%\nCollaborated with cross-functional teams'
    })
  }
}));

describe('AIPreview Component', () => {
  const defaultProps = {
    jobTitle: 'Software Engineer',
    company: 'Tech Company',
    isLoading: false,
    showPreview: true,
    isEnhanced: false,
    language: 'en' as const
  };

  beforeEach(() => {
    jest.clearAllMocks();
  });

  test('does not render when showPreview is false', () => {
    render(<AIPreview {...defaultProps} showPreview={false} />);
    expect(screen.queryByText(/Software Engineer/)).not.toBeInTheDocument();
  });

  test('does not render when isLoading is true', () => {
    render(<AIPreview {...defaultProps} isLoading={true} />);
    expect(screen.queryByText(/Software Engineer/)).not.toBeInTheDocument();
  });

  test('renders preview content when showPreview is true', () => {
    render(<AIPreview {...defaultProps} />);
    
    expect(screen.getByText(/Software Engineer at Tech Company/)).toBeInTheDocument();
    expect(screen.getByText(/Generated by AI/)).toBeInTheDocument();
  });

  test('displays mock bullets for software engineer role', () => {
    render(<AIPreview {...defaultProps} />);
    
    // Should show at least one bullet point
    const bullets = screen.getAllByText(/•/);
    expect(bullets.length).toBeGreaterThan(0);
    
    // Should contain software-related content
    expect(screen.getByText(/Developed and optimized/i)).toBeInTheDocument();
  });

  test('shows enhanced content when project and impact are provided', () => {
    render(
      <AIPreview 
        {...defaultProps} 
        project="E-commerce Platform"
        impact="increased sales"
        isEnhanced={true} 
      />
    );
    
    // Should contain project-specific content
    expect(screen.getByText(/E-commerce Platform/i)).toBeInTheDocument();
  });

  test('displays Vietnamese content when language is vi', () => {
    render(<AIPreview {...defaultProps} language="vi" />);
    
    expect(screen.getByText(/Software Engineer tại Tech Company/)).toBeInTheDocument();
    expect(screen.getByText(/Được tạo bởi AI/)).toBeInTheDocument();
  });

  test('renders different content for different job titles', () => {
    const { rerender } = render(
      <AIPreview {...defaultProps} jobTitle="Marketing Manager" />
    );
    
    expect(screen.getByText(/Marketing Manager at Tech Company/)).toBeInTheDocument();
    
    // Check for marketing-specific content
    rerender(<AIPreview {...defaultProps} jobTitle="Data Analyst" />);
    expect(screen.getByText(/Data Analyst at Tech Company/)).toBeInTheDocument();
  });

  test('handles real AI generation when useRealAI is enabled', async () => {
    render(<AIPreview {...defaultProps} useRealAI={true} />);
    
    // Initial state should show mock content
    expect(screen.getByText(/Software Engineer at Tech Company/)).toBeInTheDocument();
    
    // Real AI content will be loaded asynchronously
    // Since we mocked the service, we can't test the actual async behavior here
    // but the component should handle it gracefully
  });

  test('applies correct styling and structure', () => {
    render(<AIPreview {...defaultProps} />);
    
    // Check for AI badge
    const aiBadge = screen.getByText(/Generated by AI/);
    expect(aiBadge.closest('.bg-green-100')).toBeInTheDocument();
    
    // Check for proper bullet point structure
    const bulletContainer = screen.getByRole('list');
    expect(bulletContainer).toHaveClass('space-y-3');
  });

  test('handles empty job title gracefully', () => {
    render(<AIPreview {...defaultProps} jobTitle="" />);
    
    // Should not crash and should render general content
    expect(screen.getByText(/Generated by AI/)).toBeInTheDocument();
  });

  test('handles empty company gracefully', () => {
    render(<AIPreview {...defaultProps} company="" />);
    
    // Should not crash and should render content without company
    expect(screen.getByText(/Software Engineer/)).toBeInTheDocument();
  });
});
