export const cvEditor = {
  sectionTitles: {
    contact: 'Contact Information',
    summary: 'Professional Summary',
    experience: 'Work Experience',
    skills: 'Skills',
    education: 'Education',
    projects: 'Projects',
    achievements: 'Achievements',
    languages: 'Languages',
    certifications: 'Certifications',
  },
  header: {
    backToWorkspace: 'Back to CV Workspace',
    autoSave: {
      saving: 'Saving...',
      saved: 'Auto-saved',
      error: 'Save failed',
      offline: 'Offline mode',
    },
    userMenu: {
      profile: 'Profile',
      settings: 'Settings',
      logout: 'Sign Out',
    },
  },
  editorPanel: {
    title: 'Edit CV',
    addSection: 'Add New Section',
    deleteSection: 'Delete Section',
    reorderSections: 'Drag to reorder sections',
    cvScore: {
      title: 'CV Score',
      outOf: 'out of 100',
      improving: 'Keep improving!',
    },
    jobAnalysis: {
      title: 'Job Description Analysis',
      placeholder: 'Paste job description here to get optimization suggestions...',
      analyzeButton: 'Analyze Job',
      analyzing: 'Analyzing...',
      maxLength: 'Maximum 5000 characters',
      errors: {
        required: 'Please enter job description to analyze',
        tooLong: 'Job description too long (maximum 5000 characters)',
        analysisFailed: 'Analysis failed. Please try again.',
      },
    },
    suggestions: {
      title: 'Optimization Suggestions',
      apply: 'Apply',
      dismiss: 'Dismiss',
      noSuggestions: 'No suggestions available',
    },
  },
  sections: {
    contact: {
      title: 'Contact Information',
      fields: {
        fullName: 'Full Name',
        email: 'Email',
        phone: 'Phone',
        location: 'Location',
        linkedin: 'LinkedIn Profile',
        website: 'Website',
      },
      placeholders: {
        fullName: 'Your full name',
        email: 'your.email@example.com',
        phone: '+1 (555) 123-4567',
        location: 'City, State/Country',
        linkedin: 'linkedin.com/in/yourprofile',
        website: 'yourwebsite.com',
      },
    },
    summary: {
      title: 'Professional Summary',
      placeholder: 'Write a compelling summary that highlights your key strengths and career objectives...',
      aiHelper: 'Generate with AI',
      characterCount: 'characters',
      recommended: 'Recommended: 150-300 characters',
    },
    experience: {
      title: 'Work Experience',
      addExperience: 'Add Work Experience',
      fields: {
        title: 'Job Title',
        company: 'Company',
        location: 'Location',
        startDate: 'Start Date',
        endDate: 'End Date',
        current: 'I currently work here',
        description: 'Job Description',
        achievements: 'Key Achievements',
      },
      placeholders: {
        title: 'e.g., Software Engineer',
        company: 'e.g., Tech Company Inc.',
        location: 'e.g., San Francisco, CA',
        startDate: 'MM/YYYY',
        endDate: 'MM/YYYY',
        description: 'Describe your main responsibilities and duties...',
        achievements: 'List your key achievements and accomplishments...',
      },
      bullets: {
        add: 'Add Achievement',
        placeholder: 'Describe a specific achievement or responsibility...',
        remove: 'Remove',
        aiGenerate: 'Generate with AI',
      },
    },
    skills: {
      title: 'Skills',
      addSkill: 'Add Skill',
      categories: {
        technical: 'Technical Skills',
        soft: 'Soft Skills',
        languages: 'Languages',
        tools: 'Tools & Software',
      },
      placeholder: 'e.g., JavaScript, Project Management, Spanish',
      aiSuggestions: 'Get AI Suggestions',
    },
    education: {
      title: 'Education',
      addEducation: 'Add Education',
      fields: {
        degree: 'Degree',
        institution: 'Institution',
        location: 'Location',
        graduationDate: 'Graduation Date',
        gpa: 'GPA (optional)',
        description: 'Description',
      },
      placeholders: {
        degree: 'e.g., Bachelor of Science in Computer Science',
        institution: 'e.g., University of California',
        location: 'e.g., Berkeley, CA',
        graduationDate: 'MM/YYYY',
        gpa: 'e.g., 3.8/4.0',
        description: 'Relevant coursework, honors, activities...',
      },
    },
  },
  preview: {
    title: 'CV Preview',
    pageCounter: 'Page {{current}} of {{total}}',
    actions: {
      download: 'Download PDF',
      print: 'Print',
      share: 'Share',
    },
    downloading: 'Preparing download...',
    formats: {
      pdf: 'PDF',
      word: 'Word',
    },
  },
  notifications: {
    parsing: {
      success: 'CV Successfully Parsed!',
      successMessage: 'Your CV has been analyzed and populated automatically.',
      error: 'Parsing Failed',
      errorMessage: 'Unable to extract CV information. Please fill manually.',
    },
    save: {
      success: 'CV saved successfully',
      error: 'Failed to save CV',
      offline: 'Changes saved locally (offline)',
    },
  },
  errors: {
    loadFailed: 'Failed to load CV data',
    saveFailed: 'Failed to save CV',
    validationFailed: 'Please fill in required fields',
    networkError: 'Network error. Please check your connection.',
  },
} as const